export const GlobalVariable = Object.freeze({
  TITLE_NAME: 'App Menu',
  BASE_API: '/api',
  BASE_MODULE: '',
  BASE_RESOURCE: '/v1/bih/orders',
  BASE_RESOURCE_GET:'/searchOrders',
  BASE_RESOURCE_DELETE:'/deleteBin',
  BASE_RESOURCE_IMPORT_FILE:'/importOrder',
  BASE_RESOURCE_CREATE_ORDER:'/createOrder',
  BASE_RESOURCE_ChangeBooking:'/updateStatusChangeBooking',
  BASE_RESOURCE_DOWNLOAD_FILE:'/getOrderTemplate',
  BASE_RESOURCE_UPDATE_URGENT_ORDER:'/updateUrgentOrder',
  BASE_RESOURCE_GET_ERROR_ORDER: '/searchErrorOrder',
  BASE_RESOURCE_UPDATE_ERROR_ORDER: '/updateErrorOrderStatus',
  BASE_RESOURCE_PATIENT: '/v1/bih/patients',
  BASE_RESOURCE_GET_BY_ID:'/searchOrderPharmacistView',
  BASE_RESOURCE_GET_COUNT:'/searchCountItem',
  BASE_RESOURCE_CREATE: '/createOrder',
  BASE_RESOURCE_UPDATE: '/updatePatient',
  BASE_RESOURCE_GET_PATIENT:'/searchPatientById',
  BASE_RESOURCE_IMPORT_PATIENT : '/importPatient',
  BASE_RESOURCE_IMPORT_ORDER : '/importOrder',
  // BASE_RESOURCE: '/microservices',
  // DROP_DOWN_APPMENU: '/app',
  // BASE_RESOURCE_DELETE: '/delete',
  RESOURCE: '',
  MOCKUP_QUERY: '',
  ROLE_URL:'/order-management/orders-pharmacist-view'
});
